services:
    db:
        image: postgres:latest
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - flasknet
        ports:
            - 5432:5432
        env_file:
            - .env

    app:
        build:
            context: .
        image: corsproxy
        container_name: corsproxy
        environment:
            - PYTHONUNBUFFERED=1
        command: rundevserver
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - flasknet
        ports:
            - 5000:5000

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - certbot-www:/var/www/certbot
        depends_on:
            - app
        networks:
            - flasknet
        ports:
            - 80:80
            - 443:443
        restart: always

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - certbot-www:/var/www/certbot
        command: certonly --webroot --webroot-path=/var/www/certbot --email asheuh49@gmail.com --agree-tos --no-eff-email -d tccup-api.kenyasparks.com
        networks:
            - flasknet

volumes:
    postgres_data:
    certbot-etc:
    certbot-var:
    certbot-www:

networks:
    flasknet:
        driver: bridge
