services:
    db:
        image: postgres:latest
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - .env

    app:
        build:
            context: .
        image: corsproxy
        container_name: corsproxy
        environment:
            - PYTHONUNBUFFERED=1
        command: runprodserver
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - 5000:5000

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/www/certbot:/var/www/certbot
            - certbot-etc:/etc/letsencrypt
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        restart: always

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - /nginx/www/certbot:/var/www/certbot
            - certbot-etc:/etc/letsencrypt
        command: certonly --webroot --webroot-path=/var/www/certbot --email asheuh49@gmail.com --agree-tos --no-eff-email -d tccup-api.kenyasparks.com

volumes:
    postgres_data:
    certbot-etc:
