services:
    db:
        image: postgres:latest
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        network_mode: host
        ports:
            - 5432:5432
        env_file:
            - .env

    app:
        build:
            context: .
        image: corsproxy
        container_name: corsproxy
        environment:
            - PYTHONUNBUFFERED=1
        command: runserver
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - 5000:5000

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        restart: always

volumes:
    postgres_data:
