version: "3.11"

services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=tccup
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
    corsproxy:
        build:
            context: .
        image: corsproxy:latest
        container_name: corsproxy
        environment:
            - FLASK_ENV=production
            - PYTHONUNBUFFERED=1
            - DB_HOST=db
            - DB_PORT=5432
        command: runserver
        volumes:
            - .:/code
        ports:
            - 5000:5000
        depends_on:
            - db
        env_file:
            - .env

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        depends_on:
            - corsproxy

volumes:
    postgres_data:
