services:
    db:
        image: postgres:latest
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - flasknet
        ports:
            - 5432:5432
        env_file:
            - .env

    app:
        build:
            context: .
        image: corsproxy
        container_name: corsproxy
        environment:
            - PYTHONUNBUFFERED=1
        command: rundevserver
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - flasknet
        ports:
            - 5000:5000

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - flasknet
        ports:
            - 80:80
            - 443:443
        restart: always

volumes:
    postgres_data:

networks:
    flasknet:
        driver: bridge
