services:
    db:
        image: postgres:latest
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        network_mode: host
        env_file:
            - .env

    app:
        build:
            context: .
        image: cors-proxy_app
        container_name: corsproxy
        environment:
            - PYTHONUNBUFFERED=1
        command: runserver
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        network_mode: host

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        network_mode: host

volumes:
    postgres_data:
